import os

from openai import AzureOpenAI
from src.prompts.system import SYSTEM_PROMPT
import re
from src.config.settings import settings

class LLMService:
    def __init__(self):
        if settings.MODEL_PROVIDER == "azure":
            self.client = AzureOpenAI(
                api_key=settings.AZURE_OPENAI_API_KEY,
                api_version=settings.AZURE_OPENAI_API_VERSION,
                azure_endpoint=settings.AZURE_OPENAI_ENDPOINT
            )
            self.model = settings.AZURE_OPENAI_DEPLOYMENT_NAME
       

    def _fix_mermaid_syntax(self, code: str) -> str:
        """Fixes common Mermaid syntax errors generated by LLMs."""
        # Fix 1: Replace '-->|Label|>' with '-->|Label|'
        code = re.sub(r"-->\|(.*?)\|>", r"-->|\1|", code)
        
        # Fix 2: Replace 'A |> B' (inheritance) with 'A --> B' (dependency)
        # We use a negative lookbehind to ensure we don't change valid labels that might end in |> (rare)
        # But simply matching ' |> ' is usually safe in this context
        code = code.replace(" |> ", " --> ")
        
        # Fix 3: Remove trailing '>' from arrows like '-->|Label| >'
        code = re.sub(r"-->\|(.*?)\|\s*>", r"-->|\1|", code)

        # Fix 4: Fix dotted arrow with double head '-.->>' -> '-.->'
        code = code.replace("-.->>", "-.->")
        
        # Fix 5: Fix '-->|Label|-->' double arrow pattern
        code = re.sub(r"-->\|(.*?)\|-->", r"-->|\1|", code)

        return code

    def _clean_mermaid_response(self, content: str) -> str:
        """Extracts Mermaid code from markdown code blocks if present."""
        code = content
        pattern = r"```mermaid\n(.*?)\n```"
        match = re.search(pattern, content, re.DOTALL)
        if match:
            code = match.group(1).strip()
        else:
            # Fallback: try to find just code block without mermaid tag
            pattern_generic = r"```\n(.*?)\n```"
            match_generic = re.search(pattern_generic, content, re.DOTALL)
            if match_generic:
                code = match_generic.group(1).strip()
            else:
                code = content.strip()

        return self._fix_mermaid_syntax(code)

    def generate_diagram(self, description: str) -> str:
        try:
            completion = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"Create an architecture diagram for: {description}"}
                ],
                model=self.model,
                temperature=0.2, # Low temperature for more deterministic code
            )
            return self._clean_mermaid_response(completion.choices[0].message.content)
        except Exception as e:
            print(f"Error generating diagram: {e}")
            raise e

    def edit_diagram(self, current_diagram: str, instructions: str) -> str:
        try:
            prompt = f"""
Current Mermaid Diagram:
{current_diagram}

Edit Instructions:
{instructions}

Return the updated Mermaid diagram code ONLY.
"""
            completion = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                model=self.model,
                temperature=0.2,
            )
            return self._clean_mermaid_response(completion.choices[0].message.content)
        except Exception as e:
            print(f"Error editing diagram: {e}")
            raise e
